In [1]:
import pandas as pd
import ipeadatapy as ip
import datetime
import requests
import json

Entendendo a lib requests com a base da API do IPEADATA e testando algumas chamadas:

In [14]:
request = requests.get("http://www.ipeadata.gov.br/api/odata4/")
print(json.loads(request.text))

territorios_request = requests.get("http://www.ipeadata.gov.br/api/odata4/Territorios")

{'@odata.context': 'http://ipeadata.gov.br/api/odata4/$metadata', 'value': [{'name': 'Paises', 'kind': 'EntitySet', 'url': 'Paises'}, {'name': 'Metadados', 'kind': 'EntitySet', 'url': 'Metadados'}, {'name': 'Temas', 'kind': 'EntitySet', 'url': 'Temas'}, {'name': 'Territorios', 'kind': 'EntitySet', 'url': 'Territorios'}, {'name': 'Valores', 'kind': 'EntitySet', 'url': 'Valores'}, {'name': 'ValoresStr', 'kind': 'EntitySet', 'url': 'ValoresStr'}]}

In [13]:
pd.DataFrame(json.loads(territorios_request.text)['value'])

,NIVNOME,TERCODIGO,TERNOME,TERNOMEPADRAO,TERCAPITAL,TERAREA,NIVAMC
0,,,(não definido),(NAO DEFINIDO),None,NaN,None
1,Brasil,0,Brasil,BRASIL,False,8531507.6,False
2,Regiões,1,Região Norte,REGIAO NORTE,False,3869637.9,False
3,Estados,11,Rondônia,RONDONIA,False,238512.8,False
4,Municípios,1100015,Alta Floresta D'Oeste,ALTA FLORESTA D'OESTE,False,7111.8,False
...,...,...,...,...,...,...,...
19344,AMC 91-00,530010,Brasília,BRASILIA,False,5822.1,True
19345,AMC 60-00,530010,Brasília,BRASILIA,None,5822.1,True
19346,AMC 70-00,530010,Brasília,BRASILIA,False,5822.1,True
19347,Municípios,5300108,Brasília,BRASILIA,False,5822.1,False
19348,Mesorregiões,5301,Distrito Federal,DISTRITO FEDERAL,False,5822.1,False

Testando chamadas de Metadados:

In [219]:
valores_request = requests.get("http://www.ipeadata.gov.br/api/odata4/Metadados/")
metadados = pd.DataFrame(json.loads(valores_request.text)['value'])
metadados.head(2)

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
0,ABATE_ABPEAV,Abate - aves - peso das carcaças,O abate de animais é mensurado por sua quantid...,2022-06-09T17:54:02.11-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True
1,ABATE_ABPEBV,Abate - bovinos - peso das carcaças,O abate de animais é mensurado por sua quantid...,2022-06-09T17:10:01.89-03:00,Macroeconômico,IBGE/Coagro,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,Tonelada,mil,A,1,BRA,True

In [224]:
metadados.loc[(metadados.SERCODIGO.str.contains('IPCA'))&(metadados.FNTURL.str.contains('ibge'))].head(10)

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
5008,PRECOS_IPCAG,IPCA - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-01-12T08:30:01.28-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,(% a.a.),None,A,9,BRA,True
5020,PRECOS12_IPCA12,IPCA - geral - índice (dez. 1993 = 100),O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,-,None,A,9,BRA,True
5021,PRECOS12_IPCA15G12,IPCA - 15 - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5022,PRECOS12_IPCAAB12,IPCA - alimentos e bebidas - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5023,PRECOS12_IPCAAR12,IPCA - artigos de residência - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5024,PRECOS12_IPCACD12,IPCA - despesas pessoais - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5025,PRECOS12_IPCACO12,IPCA - comunicação - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5026,PRECOS12_IPCAED12,"IPCA - educação, leitura e papelaria - taxa de...",O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5027,PRECOS12_IPCAG12,IPCA - geral - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True
5028,PRECOS12_IPCAHA12,IPCA - habitação - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-06-09T14:36:01.327-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Mensal,(% a.m.),None,A,9,BRA,True

Chamadas de Metadados relacionados ao IPCA ANUAL:

In [113]:
metadados[(metadados['SERCODIGO'].str.contains("IPCA"))&(metadados['PERNOME']=='Anual')]

,SERCODIGO,SERNOME,SERCOMENTARIO,SERATUALIZACAO,BASNOME,FNTSIGLA,FNTNOME,FNTURL,PERNOME,UNINOME,MULNOME,SERSTATUS,TEMCODIGO,PAICODIGO,SERNUMERICA
5008,PRECOS_IPCAG,IPCA - taxa de variação,O Índice Nacional de Preços ao Consumidor Ampl...,2022-01-12T08:30:01.28-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,(% a.a.),None,A,9,BRA,True
5979,IFS_IPCALE,IPC - índice (média 2005 = 100),Índice de Preços ao Consumidor (IPC). No orig...,2017-02-06T16:58:39-02:00,Macroeconômico,FMI/IFS,"Fundo Monetário Internacional, International F...",www.imf.org,Anual,-,None,I,11,DEU,True
5980,IFS_IPCARG,IPC - índice (média 2005 = 100),Índice de Preços ao Consumidor (IPC). No orig...,2017-02-06T16:58:39-02:00,Macroeconômico,FMI/IFS,"Fundo Monetário Internacional, International F...",www.imf.org,Anual,-,None,I,11,ARG,True
7064,PAN_IPCAG,Índice de Preços ao Consumidor Ampliado (IPCA),Índice Nacional de Preços ao Consumidor Amplo ...,2022-01-12T08:30:01.28-03:00,Macroeconômico,IBGE/SNIPC,Instituto Brasileiro de Geografia e Estatístic...,www.ibge.gov.br,Anual,(% a.a.),None,A,17,BRA,True

Chamando uma série IPCA em específico (ibge):

In [8]:
serie_ipca_anual= "PRECOS_IPCAG"
serie_ipca_mensal = "PRECOS12_IPCA15G12"
pos_fix_anual = "('%s')" % serie_ipca_anual if serie_ipca_anual is not None else ""
pos_fix_mensal = "('%s')"% serie_ipca_mensal if serie_ipca_mensal is not None else ""
serie_anual_url = "http://www.ipeadata.gov.br/api/odata4/Metadados%s" % pos_fix_anual + '/Valores'
serie_mensal_url =  "http://www.ipeadata.gov.br/api/odata4/Metadados%s" % pos_fix_mensal+ '/Valores'
print(serie_anual_url)
print(serie_mensal_url)

http://www.ipeadata.gov.br/api/odata4/Metadados('PRECOS_IPCAG')/Valores
http://www.ipeadata.gov.br/api/odata4/Metadados('PRECOS12_IPCA15G12')/Valores

In [9]:
import requests
import pandas as pd
import json

ipca_mensal = requests.get(serie_mensal_url)
ipca_mensal_df = pd.DataFrame(json.loads(ipca_mensal.text)['value'])
ipca_mensal_df['VALDATA'] = pd.to_datetime(ipca_mensal_df['VALDATA'].apply(pd.to_datetime), utc=True)
ipca_mensal_df.head()

            SERCODIGO                   VALDATA  VALVALOR NIVNOME TERCODIGO
0  PRECOS12_IPCA15G12 2000-05-01 03:00:00+00:00      0.09
1  PRECOS12_IPCA15G12 2000-06-01 03:00:00+00:00      0.08
2  PRECOS12_IPCA15G12 2000-07-01 03:00:00+00:00      0.78
3  PRECOS12_IPCA15G12 2000-08-01 03:00:00+00:00      1.99
4  PRECOS12_IPCA15G12 2000-09-01 03:00:00+00:00      0.45

In [10]:
ipca_anual = requests.get(serie_anual_url)
ipca_anual_df = pd.DataFrame(json.loads(ipca_anual.text)['value'])
ipca_anual_df['VALDATA'] = pd.to_datetime(ipca_anual_df['VALDATA'].apply(pd.to_datetime), utc=True)
ipca_anual_df.head()

      SERCODIGO                   VALDATA    VALVALOR NIVNOME TERCODIGO
0  PRECOS_IPCAG 1980-01-01 02:00:00+00:00   99.250489
1  PRECOS_IPCAG 1981-01-01 02:00:00+00:00   95.623044
2  PRECOS_IPCAG 1982-01-01 02:00:00+00:00  104.790433
3  PRECOS_IPCAG 1983-01-01 02:00:00+00:00  164.012024
4  PRECOS_IPCAG 1984-01-01 02:00:00+00:00  215.263326

In [1]:
import pandas as pd
#Valores nominais do financiamento rural
financiamento_rural_nominal = [15.490, 12.005, 17.011, 26.978, 30.322, 35.533, 42.815, 49.340, 63.682, 67.166, 77.639, 93.207, 112.263, 150.139, 170.401, 178.902, 185.067, 163.199, 171.849, 169.651, 181.110]
#IPCA acumulado(mês de dezembro) de 2000 a 2020
ipca_acumulado = [5.97, 7.67, 12.53, 9.30, 7.60, 5.69, 3.14, 4.46, 5.90, 4.31, 5.91, 6.50, 5.84, 5.91, 6.41, 10.67, 6.29, 2.95, 3.75, 4.31, 4.52]
ano = [i for i in range(2000,2021)]
df = pd.DataFrame({'valor':financiamento_rural_nominal,'ipca_periodo':ipca_acumulado,'ano':ano})
df = df[['ano','valor','ipca_periodo']]

deflator = df.loc[df.ano==2018,'ipca_periodo'].squeeze()

#df['valor_deflacionado_2018'] = df['valor'] * (deflator/df['ipca_periodo'].squeeze())
#df['valor_teste'] = 10.0
#df['teste_deflacao'] = df['valor_teste'] * (deflator/df['ipca_periodo'].squeeze())
#df.head(3)

In [4]:
test_df = df[['ano','valor']]
test_df.head()

    ano   valor
0  2000  15.490
1  2001  12.005
2  2002  17.011
3  2003  26.978
4  2004  30.322

In [20]:
pd.merge(left=test_df, right=data, left_on='ano', right_on='date', how='left')

     ano    valor        series  date      value
0   2000   15.490  PRECOS_IPCAG  2000   5.974593
1   2001   12.005  PRECOS_IPCAG  2001   7.673436
2   2002   17.011  PRECOS_IPCAG  2002  12.530273
3   2003   26.978  PRECOS_IPCAG  2003   9.300513
4   2004   30.322  PRECOS_IPCAG  2004   7.599496
5   2005   35.533  PRECOS_IPCAG  2005   5.689227
6   2006   42.815  PRECOS_IPCAG  2006   3.141516
7   2007   49.340  PRECOS_IPCAG  2007   4.457659
8   2008   63.682  PRECOS_IPCAG  2008   5.902724
9   2009   67.166  PRECOS_IPCAG  2009   4.311650
10  2010   77.639  PRECOS_IPCAG  2010   5.908689
11  2011   93.207  PRECOS_IPCAG  2011   6.503353
12  2012  112.263  PRECOS_IPCAG  2012   5.838595
13  2013  150.139  PRECOS_IPCAG  2013   5.910683
14  2014  170.401  PRECOS_IPCAG  2014   6.407471
15  2015  178.902  PRECOS_IPCAG  2015  10.673028
16  2016  185.067  PRECOS_IPCAG  2016   6.287988
17  2017  163.199  PRECOS_IPCAG  2017   2.947421
18  2018  171.849  PRECOS_IPCAG  2018   3.745581
19  2019  169.651  PRECOS_IPCAG  2019   4.306152
20  2020  181.110  PRECOS_IPCAG  2020   4.517457

In [2]:
import datetime as dt
deflate_year=2022
deflate_month=8

date = dt.datetime(deflate_year, deflate_month,1)

In [12]:
date.strftime("%Y")

'2022'

In [5]:
from api_call import api_call
import pandas as pd
data = api_call(series='yearly')
data['date'] = data['date'].dt.strftime("%Y").astype('Int64')
#data['date'] = pd.to_datetime(data['date'])
print(data.dtypes)
data.head()

series     object
date        Int64
ipca      float64
dtype: object

         series  date        ipca
0  PRECOS_IPCAG  1980   99.250489
1  PRECOS_IPCAG  1981   95.623044
2  PRECOS_IPCAG  1982  104.790433
3  PRECOS_IPCAG  1983  164.012024
4  PRECOS_IPCAG  1984  215.263326

In [9]:
import pandas as pd
from datetime import datetime as dt
date = pd.to_datetime(dt(1996,1,1))
data.loc[data.date ==date]['value'].squeeze()

/home/thiago/anaconda3/envs/data/lib/python3.9/site-packages/pandas/core/ops/array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

9.56495181758998